version: '3'
services:
  #PHP Service
  vimily_app:
    image: vimily/laravel
    container_name: vimily_app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./api/:/var/www:z
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini:z
    networks:
      - app-network
    command: |
      -wait tcp://vimily_db:3306 -timeout 1m ./run.sh
    user: '1000'

  #Nginx Service
  vimily_web:
    image: nginx:alpine
    container_name: vimily_web
    restart: unless-stopped
    tty: true
    ports:
      - "8000:80"
      - "443:443"
    volumes:
      - ./api/:/var/www:z
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/:z
    networks:
      - app-network

  #MySQL Service
  vimily_db:
    image: mysql:5.7
    container_name: vimily_db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf:z
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
